services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./custom_components/zenkit:/config/custom_components/zenkit
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8123:8123"